site_name: SWM341应用指南
theme:
  name: material
repo_url: https://github.com/yanmowudi/diy-swm341
nav:
  - 前言: 'index.md'
  - 目录: '目录.md'
  - GPIO: 
    - GPIO: 'GPIO/GPIO.md'
    - EXTI: 'GPIO/EXTI.md'
  - LVGL: 'LVGL/LVGL.md'
  