# Project information
site_name: SWM341应用指南
site_url: https://yanmowudi.github.io/diy-swm341/
site_author: Lik
site_description: >-
  SWM341应用指南

# Repository
repo_name: yanmowudi/diy-swm341
repo_url: https://github.com/yanmowudi/diy-swm341
edit_uri: ""

# Configuration
theme:
  name: material
  language: zh
  palette: 
    - scheme: slate 
      primary: light blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: light green
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: images/logo.png
  favicon: images/logo.png

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanmowudi
      name: yanmowudi on github

# Page tree
nav:
  - 前言: 'index.md'
  - 目录: '目录.md'
  - GPIO: 
    - GPIO: 'GPIO/GPIO.md'
    - EXTI: 'GPIO/EXTI.md'
  - LVGL: 'LVGL/LVGL.md'
  